name: Docker Hub Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push ${{ matrix.image-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image-version: openjdk25
            java-version: 25-jre-alpine
            tags: |
              aceheliflyer/papermc:latest
              aceheliflyer/papermc:openjdk25
            description: OpenJDK25 build for newer versions.
          - image-version: openjdk21
            java-version: 21-jre-alpine
            tags: aceheliflyer/papermc:openjdk21
            description: OpenJDK21 build for older versions.
          - image-version: openjdk17
            java-version: 17-jre-alpine
            tags: aceheliflyer/papermc:openjdk17
            description: OpenJDK17 build for older versions.
          - image-version: openjdk11
            java-version: 11-jre-alpine
            tags: aceheliflyer/papermc:openjdk11
            description: OpenJDK11 build for older versions.
          - image-version: openjdk8
            java-version: 8-jre-alpine
            tags: aceheliflyer/papermc:openjdk8
            description: OpenJDK8 build for older versions.

    steps:
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # https://github.com/marketplace/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and Push ${{ matrix.image-version }}
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ matrix.tags }}
          platforms: linux/amd64
          build-args: JAVA_VERSION=${{ matrix.java-version }}
          cache-from: type=registry,ref=aceheliflyer/papermc:${{ matrix.image-version }}
          cache-to: type=inline
