name: Update Docker Hub Description

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v7

    # https://github.com/peter-evans/dockerhub-description
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v5
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: aceheliflyer/papermc
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
