name: OpenJDK11 Build

# OpenJDK11 build is for older versions of PaperMC/Minecraft.

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout is redundant not needed: https://github.com/marketplace/actions/build-and-push-docker-images#usage
      - # https://github.com/marketplace/actions/docker-setup-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - # https://github.com/marketplace/actions/docker-setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - # https://github.com/marketplace/actions/docker-login
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - # https://github.com/marketplace/actions/build-and-push-docker-images
        name: Build and Push Java 11
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: aceheliflyer/papermc:openjdk11
          platforms: linux/amd64,linux/arm64
          build-args: JAVA_VERSION=openjdk11-jre-headless
          cache-from: type=registry,ref=aceheliflyer/papermc:openjdk11
          cache-to: type=inline
